"use client";

import { useMemo, useState, useTransition, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Check, CircleCheckBig, Edit3, Plus, Trash2 } from "lucide-react";

import { changeTaskStatusAction, createTaskAction, deleteTaskAction, updateTaskAction, type WorkActionResult } from "@/app/actions/work-management";
import { PageHeader } from "@/components/layout/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import type { TaskRow } from "@/lib/data/supabase/operational";
import type { WorkManagementSnapshot } from "@/lib/data/supabase/work-management";
import { filterOperationalTasks, type TaskTimeFilter } from "@/lib/data/work-management";
import { PRIORITIES, TASK_STATUSES, WAITING_REASONS } from "@/lib/validation/work-management";

const STATUS_LABELS: Record<string, string> = { todo: "Por fazer", in_progress: "Em curso", waiting_on_client: "Aguardar cliente", blocked: "Bloqueada", done: "Concluída" };
const PRIORITY_LABELS: Record<string, string> = { low: "Baixa", normal: "Normal", high: "Alta" };
const WAITING_LABELS: Record<string, string> = { content: "Conteúdo", photos: "Fotografias", approval: "Aprovação", payment: "Pagamento", access_login: "Acessos", response: "Resposta", other: "Outro" };
const TIME_FILTERS: { value: TaskTimeFilter; label: string }[] = [{ value: "all", label: "Todas" }, { value: "mine", label: "Minhas" }, { value: "today", label: "Hoje" }, { value: "overdue", label: "Atrasadas" }, { value: "upcoming", label: "Próximas" }, { value: "completed", label: "Concluídas" }];

interface Props { snapshot: WorkManagementSnapshot; currentUserId: string; today: string; }

export function OperationalTasks({ snapshot, currentUserId, today }: Props) {
  const [dialog, setDialog] = useState<TaskRow | "new" | null>(null); const [notice, setNotice] = useState("");
  const [time, setTime] = useState<TaskTimeFilter>("all"); const [query, setQuery] = useState(""); const [owner, setOwner] = useState(""); const [priority, setPriority] = useState(""); const [status, setStatus] = useState("");
  const filtered = useMemo(() => filterOperationalTasks(snapshot.tasks, { today, currentUserId, time, query, responsibleUserId: owner || undefined, priority: priority || undefined, status: status || undefined }), [snapshot.tasks, today, currentUserId, time, query, owner, priority, status]);
  function success(message: string) { setNotice(message); setTimeout(() => setNotice(""), 3500); }
  return <div className="flex flex-col gap-6"><PageHeader title="Tarefas" description="Trabalho operacional com responsáveis, prazos e relações reais." action={<Button onClick={() => setDialog("new")}><Plus />Nova tarefa</Button>} />
    {notice && <p role="status" className="rounded-md border border-success/40 bg-success/10 p-3 text-sm text-success">{notice}</p>}
    <div className="space-y-3 rounded-lg border border-border bg-card p-4"><div className="flex gap-2 overflow-x-auto pb-1">{TIME_FILTERS.map((item) => <Button key={item.value} size="sm" variant={time === item.value ? "default" : "outline"} onClick={() => setTime(item.value)}>{item.label}</Button>)}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Input aria-label="Pesquisar tarefas" placeholder="Pesquisar tarefas…" value={query} onChange={(e) => setQuery(e.target.value)} /><Select aria-label="Filtrar por responsável" value={owner} onChange={(e) => setOwner(e.target.value)}><option value="">Todos os responsáveis</option>{snapshot.users.map((u) => <option key={u.user_id} value={u.user_id}>{u.display_name}</option>)}</Select><Select aria-label="Filtrar por prioridade" value={priority} onChange={(e) => setPriority(e.target.value)}><option value="">Todas as prioridades</option>{PRIORITIES.map((v) => <option key={v} value={v}>{PRIORITY_LABELS[v]}</option>)}</Select><Select aria-label="Filtrar por estado" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Todos os estados</option>{TASK_STATUSES.map((v) => <option key={v} value={v}>{STATUS_LABELS[v]}</option>)}</Select></div></div>
    {filtered.length === 0 ? <EmptyState icon={CircleCheckBig} title="Sem tarefas para mostrar" description="Cria uma tarefa ou ajusta os filtros." action={<Button onClick={() => setDialog("new")}><Plus />Nova tarefa</Button>} /> : <div className="space-y-3">{filtered.map((task) => <TaskCard key={task.id} task={task} snapshot={snapshot} onEdit={() => setDialog(task)} onSuccess={success} />)}</div>}
    {dialog && <TaskFormDialog key={dialog === "new" ? "new" : dialog.id} open task={dialog === "new" ? undefined : dialog} snapshot={snapshot} currentUserId={currentUserId} onOpenChange={(open) => !open && setDialog(null)} onSuccess={success} />}
  </div>;
}

function TaskCard({ task, snapshot, onEdit, onSuccess }: { task: TaskRow; snapshot: WorkManagementSnapshot; onEdit: () => void; onSuccess: (message: string) => void; }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const owner = snapshot.users.find((u) => u.user_id === task.responsible_user_id)?.display_name ?? "Responsável indisponível";
  const relation = task.business_id ? snapshot.businesses.find((x) => x.id === task.business_id)?.name : task.project_id ? snapshot.projects.find((x) => x.id === task.project_id)?.name : task.deal_id ? snapshot.deals.find((x) => x.id === task.deal_id)?.title : null;
  const goals = snapshot.goalTasks.filter((link) => link.task_id === task.id).map((link) => snapshot.goals.find((goal) => goal.id === link.goal_id)?.name).filter(Boolean);
  function mutate(operation: () => Promise<WorkActionResult>) { startTransition(async () => { const next = await operation(); if (next.ok) { onSuccess(next.message); router.refresh(); } }); }
  return <Card><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><button type="button" aria-label={task.status === "done" ? "Reabrir tarefa" : "Concluir tarefa"} className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-border" disabled={pending} onClick={() => mutate(() => changeTaskStatusAction(task.id, task.status === "done" ? "todo" : "done"))}>{task.status === "done" && <Check />}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className={task.status === "done" ? "font-medium line-through text-muted-foreground" : "font-medium"}>{task.title}</p><Badge variant={task.status === "done" ? "success" : task.status === "blocked" ? "destructive" : task.status === "in_progress" ? "info" : "muted"}>{STATUS_LABELS[task.status]}</Badge><Badge variant="outline">{PRIORITY_LABELS[task.priority]}</Badge></div>{task.description && <p className="mt-1 text-sm text-muted-foreground">{task.description}</p>}<p className="mt-1 text-xs text-muted-foreground">{owner}{task.due_date ? ` · prazo ${task.due_date}` : " · sem prazo"}{relation ? ` · ${relation}` : ""}{goals.length ? ` · ${goals.join(", ")}` : ""}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={onEdit}><Edit3 />Editar</Button><Button size="icon" variant="ghost" aria-label="Eliminar tarefa" disabled={pending} onClick={() => { if (window.confirm(`Eliminar a tarefa “${task.title}”?`)) mutate(() => deleteTaskAction(task.id)); }}><Trash2 /></Button></div></CardContent></Card>;
}

function TaskFormDialog({ task, snapshot, currentUserId, open, onOpenChange, onSuccess }: { task?: TaskRow; snapshot: WorkManagementSnapshot; currentUserId: string; open: boolean; onOpenChange: (open: boolean) => void; onSuccess: (message: string) => void; }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [result, setResult] = useState<WorkActionResult | null>(null);
  const [title, setTitle] = useState(task?.title ?? ""); const [description, setDescription] = useState(task?.description ?? ""); const [status, setStatus] = useState(task?.status ?? "todo"); const [waitingReason, setWaitingReason] = useState(task?.waiting_reason ?? ""); const [priority, setPriority] = useState(task?.priority ?? "normal"); const [dueDate, setDueDate] = useState(task?.due_date ?? ""); const [owner, setOwner] = useState(task?.responsible_user_id ?? (snapshot.users.some((u) => u.user_id === currentUserId) ? currentUserId : snapshot.users[0]?.user_id ?? ""));
  const initialRelation = task?.business_id ? "business" : task?.project_id ? "project" : task?.deal_id ? "deal" : "none"; const [relationType, setRelationType] = useState(initialRelation); const [relationId, setRelationId] = useState(task?.business_id ?? task?.project_id ?? task?.deal_id ?? "");
  const [goalIds, setGoalIds] = useState<string[]>(task ? snapshot.goalTasks.filter((link) => link.task_id === task.id).map((link) => link.goal_id) : []);
  const relationOptions = relationType === "business" ? snapshot.businesses.map((x) => ({ id: x.id, label: x.name })) : relationType === "project" ? snapshot.projects.map((x) => ({ id: x.id, label: x.name })) : relationType === "deal" ? snapshot.deals.map((x) => ({ id: x.id, label: x.title })) : [];
  function submit(e: FormEvent) { e.preventDefault(); setResult(null); startTransition(async () => { const input = { title, description, status: status as never, waitingReason: status === "waiting_on_client" ? (waitingReason || null) as never : null, priority: priority as never, dueDate: dueDate || null, responsibleUserId: owner, businessId: relationType === "business" ? relationId || null : null, projectId: relationType === "project" ? relationId || null : null, dealId: relationType === "deal" ? relationId || null : null, goalIds }; const next = task ? await updateTaskAction(task.id, input) : await createTaskAction(input); setResult(next); if (next.ok) { onSuccess(next.message); router.refresh(); onOpenChange(false); } }); }
  return <Dialog open={open} onOpenChange={pending ? undefined : onOpenChange}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>{task ? "Editar tarefa" : "Nova tarefa"}</DialogTitle><DialogDescription>Define o trabalho, prazo, responsável e contexto operacional.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><Field label="Título" required><Input autoFocus required value={title} onChange={(e) => setTitle(e.target.value)} /></Field><Field label="Descrição"><Textarea rows={3} value={description} onChange={(e) => setDescription(e.target.value)} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Estado"><Select value={status} onChange={(e) => { setStatus(e.target.value); if (e.target.value !== "waiting_on_client") setWaitingReason(""); }}>{TASK_STATUSES.map((v) => <option key={v} value={v}>{STATUS_LABELS[v]}</option>)}</Select></Field>{status === "waiting_on_client" && <Field label="Motivo de espera" required><Select required value={waitingReason} onChange={(e) => setWaitingReason(e.target.value)}><option value="">Selecionar…</option>{WAITING_REASONS.map((v) => <option key={v} value={v}>{WAITING_LABELS[v]}</option>)}</Select></Field>}<Field label="Prioridade"><Select value={priority} onChange={(e) => setPriority(e.target.value)}>{PRIORITIES.map((v) => <option key={v} value={v}>{PRIORITY_LABELS[v]}</option>)}</Select></Field><Field label="Prazo"><Input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} /></Field><Field label="Responsável" required><Select required value={owner} onChange={(e) => setOwner(e.target.value)}><option value="">Selecionar…</option>{snapshot.users.map((u) => <option key={u.user_id} value={u.user_id}>{u.display_name}</option>)}</Select></Field><Field label="Tipo de relação"><Select value={relationType} onChange={(e) => { setRelationType(e.target.value); setRelationId(""); }}><option value="none">Sem relação</option><option value="business">Business</option><option value="project">Project</option><option value="deal">Deal</option></Select></Field>{relationType !== "none" && <Field label="Registo relacionado" required><Select required value={relationId} onChange={(e) => setRelationId(e.target.value)}><option value="">Selecionar…</option>{relationOptions.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</Select></Field>}</div>
      <fieldset className="rounded-lg border border-border p-3"><legend className="px-1 text-sm font-medium">Objetivos relacionados</legend><div className="mt-2 grid max-h-36 gap-2 overflow-y-auto sm:grid-cols-2">{snapshot.goals.length ? snapshot.goals.map((goal) => <label key={goal.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={goalIds.includes(goal.id)} onChange={() => setGoalIds((ids) => ids.includes(goal.id) ? ids.filter((id) => id !== goal.id) : [...ids, goal.id])} />{goal.name}</label>) : <p className="text-sm text-muted-foreground">Ainda não existem objetivos.</p>}</div></fieldset>
      {result && !result.ok && <p role="alert" className="rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{result.message}</p>}<DialogFooter><Button type="button" variant="outline" disabled={pending} onClick={() => onOpenChange(false)}>Cancelar</Button><Button type="submit" disabled={pending || !title.trim() || !owner || (relationType !== "none" && !relationId)}>{pending ? "A guardar…" : task ? "Guardar alterações" : "Criar tarefa"}</Button></DialogFooter></form></DialogContent></Dialog>;
}

function Field({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) { return <Label className="flex flex-col items-stretch gap-1.5"><span>{label}{required ? " *" : ""}</span>{children}</Label>; }
